"""Unicode Length tittle

Revision ID: 3f90b795b9eb
Revises: 15c56a5615d8
Create Date: 2015-09-23 13:42:47.954602

"""

# revision identifiers, used by Alembic.
revision = '3f90b795b9eb'
down_revision = '15c56a5615d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_artist', 'artist_name',  type_=sa.Unicode(255))
    op.alter_column('tb_author', 'author_name',  type_=sa.Unicode(255))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_artist', 'artist_name',  type_=sa.Unicode(100))
    op.alter_column('tb_author', 'author_name',  type_=sa.Unicode(100))
    ### end Alembic commands ###
